// <auto-generated />
using System;
using BeitPatissierServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeitPatissierServer.Migrations
{
    [DbContext(typeof(BeitPatissierContext))]
    [Migration("20251130125120_add_Category_table")]
    partial class add_Category_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeitPatissierServer.Models.Allergen", b =>
                {
                    b.Property<int>("AllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergenId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllergenId");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            AllergenId = 1,
                            Name = "גלוטן"
                        },
                        new
                        {
                            AllergenId = 2,
                            Name = "אגוזים"
                        },
                        new
                        {
                            AllergenId = 3,
                            Name = "ביצים"
                        },
                        new
                        {
                            AllergenId = 4,
                            Name = "חלב"
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.BPUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordResetCodeExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4661ac7-6c89-4f7a-b667-fe73add76f64",
                            Email = "manager1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Mali",
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Levi",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER1@EXAMPLE.COM",
                            NormalizedUserName = "MANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz1FJf0qV3hGm8R9TtNwftF6u4aG+Yq5rC9GxJzFm0rD2nW6D4bU6YpT2yK1J/MBw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e454667-961b-478a-baa0-4952e55696c2",
                            Email = "manager2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cohen",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER2@EXAMPLE.COM",
                            NormalizedUserName = "MANAGER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz1FJf0qV3hGm8R9TtNwftF6u4aG+Yq5rC9GxJzFm0rD2nW6D4bU6YpT2yK1J/MBw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "manager2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ef5a99e-61af-4b76-a4b2-3e72a1bf10a4",
                            Email = "customer1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Avi",
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Halevi",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz1FJf0qV3hGm8R9TtNwftF6u4aG+Yq5rC9GxJzFm0rD2nW6D4bU6YpT2yK1J/MBw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b16151f-087a-4dba-b3a0-1b2c7baace41",
                            Email = "customer2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Rachel",
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bar",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz1FJf0qV3hGm8R9TtNwftF6u4aG+Yq5rC9GxJzFm0rD2nW6D4bU6YpT2yK1J/MBw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4dd35027-e359-4b00-89c6-cbb0e1ffc63c",
                            Email = "customer3@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            JoinDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tal",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER3@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEGz1FJf0qV3hGm8R9TtNwftF6u4aG+Yq5rC9GxJzFm0rD2nW6D4bU6YpT2yK1J/MBw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "customer3"
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "מנות ראשונות"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "מנות אחרונות"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "מגשי ארוח"
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Email = "avi@example.com",
                            Message = "לא מצליח להתחבר למערכת",
                            Phone = "0501234567",
                            Status = 0,
                            Subject = "בעיה בהתחברות",
                            UserId = 6,
                            UserName = "Avi User"
                        },
                        new
                        {
                            ContactId = 2,
                            Email = "avi@example.com",
                            Message = "הזמנה לא נסגרת",
                            Phone = "0501234567",
                            Status = 0,
                            Subject = "באג בהזמנה",
                            UserId = 6,
                            UserName = "Avi User"
                        },
                        new
                        {
                            ContactId = 3,
                            Email = "avi@example.com",
                            Message = "מבקש לעדכן טלפון",
                            Phone = "0501234567",
                            Status = 0,
                            Subject = "עדכון פרטים",
                            UserId = 4,
                            UserName = "Avi User"
                        },
                        new
                        {
                            ContactId = 4,
                            Email = "mali@example.com",
                            Message = "מתי מגיע?",
                            Phone = "0529988776",
                            Status = 0,
                            Subject = "שאלה על משלוח",
                            UserName = "Mali"
                        },
                        new
                        {
                            ContactId = 5,
                            Email = "sara@example.com",
                            Message = "הפרטים שלי לא מעודכנים",
                            Phone = "0534455667",
                            Status = 0,
                            Subject = "בקשה לתיקון",
                            UserName = "Sara"
                        },
                        new
                        {
                            ContactId = 6,
                            Email = "dan@example.com",
                            Message = "טופל",
                            Phone = "0547891122",
                            Status = 1,
                            Subject = "סגור 1",
                            UserName = "Dan"
                        },
                        new
                        {
                            ContactId = 7,
                            Email = "hadas@example.com",
                            Message = "נפתר",
                            Phone = "0585566778",
                            Status = 1,
                            Subject = "סגור 2",
                            UserName = "Hadas"
                        },
                        new
                        {
                            ContactId = 8,
                            Email = "roni@example.com",
                            Message = "הסתדר",
                            Phone = "0573322110",
                            Status = 1,
                            Subject = "סגור 3",
                            UserName = "Roni"
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "אבקת שקדים",
                            PricePerUnit = 0m
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "סוכר",
                            PricePerUnit = 0m
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "חלבון ביצה",
                            PricePerUnit = 0m
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "חמאה",
                            PricePerUnit = 0m
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "קמח",
                            PricePerUnit = 0m
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "שמרים",
                            PricePerUnit = 0m
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderLineId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3,
                            Description = "מקרון עדין משקדים במגוון טעמים.",
                            Name = "מקרון",
                            Price = 120m,
                            RecipeId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "קראוסון חמאה קלאסי וטרי.",
                            Name = "קראוסון",
                            Price = 40m,
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 2
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("AllergenId")
                        .HasColumnType("int");

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("AllergenId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CookingTime = 15,
                            Description = "מקרון חלבי עשיר בטעם פיסטוק",
                            Name = "מקרון",
                            PreparationTime = 30,
                            Servings = 12,
                            Steps = "[\"\\u05DC\\u05D4\\u05E7\\u05E6\\u05D9\\u05E3 \\u05D7\\u05DC\\u05D1\\u05D5\\u05E0\\u05D9\\u05DD\",\"\\u05DC\\u05E7\\u05E4\\u05DC \\u05D0\\u05D1\\u05E7\\u05EA \\u05E1\\u05D5\\u05DB\\u05E8 \\u05D5\\u05E9\\u05E7\\u05D3\\u05D9\\u05DD\",\"\\u05DC\\u05D6\\u05DC\\u05E3 \\u05E2\\u05D9\\u05D2\\u05D5\\u05DC\\u05D9\\u05DD\",\"\\u05DC\\u05D0\\u05E4\\u05D5\\u05EA \\u05D1\\u05D7\\u05D5\\u05DD \\u05E0\\u05DE\\u05D5\\u05DA\",\"\\u05DC\\u05DE\\u05DC\\u05D0 \\u05D1\\u05E7\\u05E8\\u05DD \\u05E4\\u05D9\\u05E1\\u05D8\\u05D5\\u05E7\"]"
                        },
                        new
                        {
                            RecipeId = 2,
                            CookingTime = 25,
                            Description = "קראוסון ממולא גבינות",
                            Name = "קראוסון",
                            PreparationTime = 120,
                            Servings = 8,
                            Steps = "[\"\\u05DC\\u05DC\\u05D5\\u05E9 \\u05D1\\u05E6\\u05E7 \\u05E9\\u05DE\\u05E8\\u05D9\\u05DD\",\"\\u05DC\\u05E7\\u05E4\\u05DC \\u05E9\\u05DB\\u05D1\\u05D5\\u05EA \\u05D7\\u05DE\\u05D0\\u05D4\",\"\\u05DC\\u05D2\\u05DC\\u05D2\\u05DC \\u05D5\\u05DC\\u05E4\\u05E8\\u05D5\\u05E1\",\"\\u05DC\\u05D4\\u05EA\\u05E4\\u05D9\\u05D7\",\"\\u05DC\\u05D0\\u05E4\\u05D5\\u05EA \\u05E2\\u05D3 \\u05D4\\u05D6\\u05D4\\u05D1\\u05D4\"]"
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.RecipeAllergen", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("RecipeAllergen");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            AllergenId = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            AllergenId = 3
                        },
                        new
                        {
                            RecipeId = 1,
                            AllergenId = 4
                        },
                        new
                        {
                            RecipeId = 2,
                            AllergenId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            AllergenId = 3
                        },
                        new
                        {
                            RecipeId = 2,
                            AllergenId = 4
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.RecipeLine", b =>
                {
                    b.Property<int>("RecipeLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeLineId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("RecipeLineId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeLines");

                    b.HasData(
                        new
                        {
                            RecipeLineId = 1,
                            IngredientId = 1,
                            Quantity = 120m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 2,
                            IngredientId = 2,
                            Quantity = 150m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 3,
                            IngredientId = 3,
                            Quantity = 3m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 4,
                            IngredientId = 4,
                            Quantity = 50m,
                            RecipeId = 1,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 5,
                            IngredientId = 5,
                            Quantity = 250m,
                            RecipeId = 2,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 6,
                            IngredientId = 2,
                            Quantity = 50m,
                            RecipeId = 2,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 7,
                            IngredientId = 4,
                            Quantity = 150m,
                            RecipeId = 2,
                            Unit = 0
                        },
                        new
                        {
                            RecipeLineId = 8,
                            IngredientId = 6,
                            Quantity = 10m,
                            RecipeId = 2,
                            Unit = 0
                        });
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagType")
                        .HasColumnType("int");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            CategoryId = 0,
                            Name = "פטיפורים",
                            TagType = 0
                        },
                        new
                        {
                            TagId = 2,
                            CategoryId = 0,
                            Name = "מאפים",
                            TagType = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Contact", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.BPUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Image", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Order", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.BPUser", "User")
                        .WithMany("UserOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.OrderLine", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Product", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.ProductTag", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Recipe", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Allergen", null)
                        .WithMany("Recipes")
                        .HasForeignKey("AllergenId");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.RecipeAllergen", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.Recipe", "Recipe")
                        .WithMany("Allergens")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.RecipeLine", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.Recipe", "Recipe")
                        .WithMany("RecipeLines")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.BPUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.BPUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeitPatissierServer.Models.BPUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BeitPatissierServer.Models.BPUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Allergen", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.BPUser", b =>
                {
                    b.Navigation("UserOrders");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Recipe", b =>
                {
                    b.Navigation("Allergens");

                    b.Navigation("RecipeLines");
                });

            modelBuilder.Entity("BeitPatissierServer.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
